apiVersion: v1
kind: Service
metadata:
  name: worker-lb
  namespace: kube-system
  annotations:
    load-balancer.hetzner.cloud/location: eu-central
    load-balancer.hetzner.cloud/name: lb-worker-0
    load-balancer.hetzner.cloud/health-check-port: "30542"
spec:
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Local
  healthCheckNodePort: 30787
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
