{
 "title": "hcloud-csi-driver",
 "tags": [
  "hcloud",
  "csi-driver",
  "kubernetes",
  "grpc"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{job=~\"hcloud-csi|hcloud-csi-controller\"}, pod)"
    }
   },
   {
    "name": "grpc_service",
    "query": {
     "query": "label_values(grpc_server_handled_total{job=~\"hcloud-csi|hcloud-csi-controller\"}, grpc_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available Pods",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "count(up{pod=~\"$pod\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Global Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handled_total{pod=~\"$pod\",grpc_type=\"unary\",grpc_code=\"OK\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{pod=~\"$pod\",grpc_type=\"unary\",grpc_code=\"NotFound\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{pod=~\"$pod\",grpc_type=\"unary\",grpc_code=\"PermissionDenied\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{pod=~\"$pod\",grpc_type=\"unary\",grpc_code=\"InvalidArgument\"}[$__rate_interval])))\n/ \nsum(rate(grpc_server_started_total{pod=~\"$pod\",grpc_type=\"unary\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CSI QPS",
   "type": "stat",
   "description": "Without csi.v1.Identity.Probe (health checks)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(grpc_server_started_total{pod=~\"$pod\",grpc_method!=\"Probe\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\",container!=\"\"}) by (pod, container)",
     "legendFormat": "{{container}} ({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(container,pod)(rate(container_cpu_usage_seconds_total{pod=~\"$pod\",container!=\"\"}[$__interval]))",
     "legendFormat": "{{container}} ({{pod}})"
    }
   ]
  },
  { "title": "CSI gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(grpc_server_started_total{pod=~\"$pod\"}[$__rate_interval])) by (grpc_service, pod)",
     "legendFormat": "{{grpc_service}} ({{pod}})"
    }
   ]
  },
  {
   "title": "Average handling time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(grpc_server_handling_seconds_sum{pod=~\"$pod\",grpc_type=\"unary\"}[$__rate_interval])) by (grpc_service, pod) * 1000",
     "legendFormat": "{{grpc_service}} ({{pod}})"
    }
   ]
  },
  {
   "title": "gRPC request code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{pod=~\"$pod\",grpc_type=\"unary\"}[$__rate_interval])) by (grpc_code, pod)",
     "legendFormat": "{{grpc_code}} ({{pod}})"
    }
   ]
  },
  {
   "title": "$grpc_service gRPC requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "grpc_service",
   "targets": [
    {}
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{pod=~\"$pod\",grpc_service=~\"$grpc_service\"}[$__rate_interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "99%-tile latency of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{pod=~\"$pod\",grpc_service=~\"$grpc_service\"}[$__rate_interval])) by (grpc_method,le)\n)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Request error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{pod=~\"$pod\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$__rate_interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Request error percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{pod=~\"$pod\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$__rate_interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{pod=~\"$pod\",grpc_service=~\"$grpc_service\"}[$__rate_interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  { "title": "Hetzner Cloud API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Requests per Endpoint",
   "type": "timeseries",
   "description": "Total number of requests made per endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, api_endpoint) (rate(hcloud_api_requests_total{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{api_endpoint}}"
    }
   ]
  },
  {
   "title": "HTTP Response Code",
   "type": "timeseries",
   "description": "Responses from Hetzner Cloud API by HTTP code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(hcloud_api_requests_total{pod=~\"$pod\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "1h Total Request",
   "type": "timeseries",
   "description": "Requests made over 1 hour window. Relevant for Rate Limiting Issues",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum(delta(hcloud_api_requests_total{pod=~\"$pod\"}[1h]))",
     "legendFormat": "Requests over 1hr window"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "sum(rate(hcloud_api_request_duration_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}