apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hcloud-csi-controller
  namespace: kube-system
  labels:
    app: hcloud-csi-controller
spec:
  endpoints:
    - port: metrics
      scheme: http
  jobLabel: app
  selector:
    matchLabels:
      app: hcloud-csi-controller

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hcloud-csi-node
  namespace: kube-system
  labels:
    app: hcloud-csi-node
spec:
  endpoints:
    - port: metrics
      scheme: http
  jobLabel: app
  selector:
    matchLabels:
      app: hcloud-csi
